--Syntax
Create or replace procedure Proc_Name()
Return Table
Language = SQL
AS
$$
 INSERT into TABLE1 ("Column1")
 select "Value1" as "column1";

 return 'Done'
 $$;
 
 Create schema if not exists MY_DB.MYPROCS;
 
 CREATE OR REPLACE TABLE MY_DB.MYPROCS.CUST_SALES
(CID INT, CNAME VARCHAR, PRODNAME VARCHAR, PROD_CAT VARCHAR, PRICE NUMBER);


INSERT INTO MY_DB.MYPROCS.CUST_SALES VALUES
(101, 'RAMU', 'REFRIGERATOR', 'ELECTRONICS', 25000 ),
(101, 'RAMU', 'TV', 'ELECTRONICS' , 33500),
(101, 'RAMU', 'MAGGIE', 'FOOD', 200),
(102, 'LATHA', 'T-SHIRT', 'FASHION', 1099),
(102, 'LATHA', 'JEANS', 'FASHION', 2999),
(102, 'LATHA', 'WALLNUTS', 'FOOD', 2000),
(102, 'LATHA', 'WASHING MACHINE', 'ELECTRONICS', 29000),
(102, 'LATHA', 'SMART WATCH', 'ELECTRONICS', 12000),
(102, 'LATHA', 'ALMOND', 'FOOD', 1500),
(102, 'LATHA', 'TOUR DAL', 'FOOD', 500),
(102, 'LATHA', 'RICE', 'FOOD', 1300);

Select * from MY_DB.MYPROCS.CUST_SALES;


//Create a procedure to calc total amount in store.

Create or replace procedure MY_DB.MYPROCS.CUST_TOTAL_PRICE(ID INT, CAT VARCHAR)
RETURNS FLOAT
LANGUAGE SQL
AS
$$

DECLARE 
TOTAL_SPENT FLOAT;
cur1 cursor for select CID, PROD_CAT, PRICE  from MY_DB.MYPROCS.CUST_SALES;

BEGIN 
TOTAL_SPENT:=0;
for i in cur1
do 
    if (i.PROD_CAT=:CAT and i.CID=:ID ) then 
        TOTAL_SPENT:=TOTAL_SPENT+i.PRICE;
    end if;    
end for; 

Return TOTAL_SPENT;
END
$$

//Call to the stored procedure
CALL MY_DB.MYPROCS.CUST_TOTAL_PRICE(101,'ELECTRONICS');
CALL MY_DB.MYPROCS.CUST_TOTAL_PRICE(101,'FOOD');
CALL MY_DB.MYPROCS.CUST_TOTAL_PRICE(102,'FOOD');
CALL MY_DB.MYPROCS.CUST_TOTAL_PRICE(102,'ELECTRONICS');
CALL MY_DB.MYPROCS.CUST_TOTAL_PRICE(102,'FASHION');
CALL MY_DB.MYPROCS.CUST_TOTAL_PRICE(103,'FASHION');

Select * from MY_DB.MYPROCS.CUST_SALES;

Select distinct CID, CNAME,PROD_CAT, SUM(PRICE) OVER (PARTITION BY CID,PROD_CAT ) FROM  MY_DB.MYPROCS.CUST_SALES;
