Create schema MY_DB.SCHEMA3;

Create OR replace table MY_DB.SCHEMA3.STG_EMPL(
EMPID INT,
  EMPNAME VARCHAR(30),
  SALARY FLOAT,
  AGE INT,
  DEPT VARCHAR(20),
  LOCATION VARCHAR(20)
);

CREATE STREAM MY_DB.SCHEMA3.STREAM_EMPL1 ON TABLE MY_DB.SCHEMA3.STG_EMPL;

CREATE STREAM MY_DB.SCHEMA3.STREAM_EMPL2 ON TABLE MY_DB.SCHEMA3.STG_EMPL;
Select * from MY_DB.SCHEMA3.STREAM_EMPL2 

show streams;
show streams in Database MY_DB ;
show streams in schema MY_DB.SCHEMA3 ;
Desc STreAM MY_DB.SCHEMA3.STREAM_EMPL1;



CREATE OR REPLACE TABLE MY_DB.SCHEMA3.TARGET_EMPL(
EMPID INT,
  EMPNAME VARCHAR(30),
  SALARY FLOAT,
  AGE INT,
  DEPT VARCHAR(20),
  LOCATION VARCHAR(20),
  INSERT_DATE DATE,
  LAST_UPDATE_DATE DATE
);

INSERT INTO MY_DB.SCHEMA3.STG_EMPL VALUES
(1, 'Amar', 80000, 35, 'SALES', 'Bangalore'),
(2, 'Bharath', 45000, 26, 'SALES', 'Hyderabad'),
(3, 'Charan', 76000, 34, 'TECHNOLOGY', 'Chennai'),
(4, 'Divya', 52000, 28, 'HR', 'Hyderabad'),
(5, 'Gopal', 24500, 22, 'TECHNOLOGY', 'Bangalore'),
(6, 'Haritha', 42000, 27, 'HR', 'Chennai') ;

Select * from MY_DB.SCHEMA3.STG_EMPL;
Select * from MY_DB.SCHEMA3.STREAM_EMPL1;
Select * from MY_DB.SCHEMA3.STREAM_EMPL2;


--consume records to target table
-- Insert
Insert into MY_DB.SCHEMA3.TARGET_EMPL
(EMPID, EMPNAME, SALARY, AGE , DEPT, LOCATION, INSERT_DATE,LAST_UPDATE_DATE) 
Select EMPID, EMPNAME, SALARY, AGE , DEPT, LOCATION, CURRENT_DATE, NULL 
from MY_DB.SCHEMA3.STREAM_EMPL1
WHERE 
METADATA$ACTION = 'INSERT' AND
METADATA$ISUPDATE = FALSE;
/*After inserting data in target table, 
stream  gets truncated and offset is moved to capture next data change */ 
Select * from MY_DB.SCHEMA3.STREAM_EMPL1;
Select * from MY_DB.SCHEMA3.TARGET_EMPL;


-- update 
update  MY_DB.SCHEMA3.STG_EMPL SET SALARY = 49000 Where EMPID=2;
update  MY_DB.SCHEMA3.STG_EMPL SET Location = 'PUNE' Where EMPID=5;

select * From MY_DB.SCHEMA3.STG_EMPL;
Select * from MY_DB.SCHEMA3.STREAM_EMPL1;
Select * from MY_DB.SCHEMA3.STREAM_EMPL2; --offset not updtaed in 2 stream as its not yet utlized

MERGE INTO MY_DB.SCHEMA3.TARGET_EMPL T
 USING MY_DB.SCHEMA3.STREAM_EMPL1 S
      ON T.EMPID=S.EMPID
 When Matched
 AND METADATA$ACTION = 'INSERT'
 AND METADATA$ISUPDATE = TRUE 
THEN UPDATE 
  SET 
  T.EMPNAME=S.EMPNAME,
  T.SALARY=S.SALARY,
  T.AGE=S.AGE,
  T.DEPT=S.DEPT,
  T.LOCATION=S.LOCATION,
  T.LAST_UPDATE_DATE=Current_DATE;

Select* from MY_DB.SCHEMA3.TARGET_EMPL;  
Select * from MY_DB.SCHEMA3.STREAM_EMPL1; 

--Delete
Delete from MY_DB.SCHEMA3.STG_EMPL Where EMPID IN (3,4);
Select * from MY_DB.SCHEMA3.STREAM_EMPL1;

MERGE INTO MY_DB.SCHEMA3.TARGET_EMPL T
USING MY_DB.SCHEMA3.STREAM_EMPL1 S
 ON T.EMPID=S.EMPID
WHEN MATCHED 
    AND METADATA$ACTION='DELETE'
    AND METADATA$ISUPDATE=FALSE
THEN DELETE;   

Select* from MY_DB.SCHEMA3.TARGET_EMPL; 


============================
---INSERT/UPDATE/DELETE TOGETHER

INSERT INTO MY_DB.SCHEMA3.STG_EMPL
VALUES 
(7,'Janki',61000, 29, 'Sales','Pune'),
(6, 'Kamal',92000,33, 'Technology','Bangaluru');

Update MY_DB.SCHEMA3.STG_EMPL SET SALARY = 85000, LOCATION ='Hyderabad' Where EMPID =1;

Delete from MY_DB.SCHEMA3.STG_EMPL Where EMPID = 6;

Select * from MY_DB.SCHEMA3.STG_EMPL;

Select * from MY_DB.SCHEMA3.STREAM_EMPL1;


MERGE INTO MY_DB.SCHEMA3.TARGET_EMPL T
USING MY_DB.SCHEMA3.STREAM_EMPL1 S
    ON T.EMPID=S.EMPID
WHEN MATCHED                              --DELETE CASE
    AND METADATA$ACTION='DELETE'
    AND METADATA$ISUPDATE=FALSE
THEN DELETE
WHEN MATCHED                              --UPADTE CASE
    AND METADATA$ACTION='INSERT'
    AND METADATA$ISUPDATE=TRUE
THEN UPDATE 
    SET
    T.EMPNAME=S.EMPNAME,
    T.SALARY=S.SALARY,
    T.AGE=S.AGE,
    T.DEPT=S.DEPT,
    T.LOCATION=S.LOCATION,
    T.LAST_UPDATE_DATE=Current_DATE
WHEN NOT MATCHED                          --INSERT CASE
    AND METADATA$ACTION='INSERT'
    AND METADATA$ISUPDATE=FALSE
THEN INSERT (EMPID,EMPNAME,SALARY,AGE,DEPT,LOCATION, INSERT_DATE,LAST_UPDATE_DATE) 
     VALUES (S.EMPID,S.EMPNAME,S.SALARY,S.AGE,S.DEPT,S.LOCATION,CURRENT_DATE,NULL);

select * from MY_DB.SCHEMA3.TARGET_EMPL



====================
--Streams with task
====================

Create or replace task MY_DB.SCHEMA3.Stream_TASK
 WAREHOUSE = WAREMINI
  SCHEDULE = '1 minute'
 --SCHEDULE = 'USING CRON 2  * * * * UTC-8'
 --After
 WHEN SYSTEM$STREAM_HAS_DATA('MY_DB.SCHEMA3.STREAM_EMPL1')
 AS 
 MERGE INTO MY_DB.SCHEMA3.TARGET_EMPL T
USING MY_DB.SCHEMA3.STREAM_EMPL1 S
    ON T.EMPID=S.EMPID
WHEN MATCHED                              --DELETE CASE
    AND METADATA$ACTION='DELETE'
    AND METADATA$ISUPDATE=FALSE
THEN DELETE
WHEN MATCHED                              --UPADTE CASE
    AND METADATA$ACTION='INSERT'
    AND METADATA$ISUPDATE=TRUE
THEN UPDATE 
    SET
    T.EMPNAME=S.EMPNAME,
    T.SALARY=S.SALARY,
    T.AGE=S.AGE,
    T.DEPT=S.DEPT,
    T.LOCATION=S.LOCATION,
    T.LAST_UPDATE_DATE=Current_DATE
WHEN NOT MATCHED                          --INSERT CASE
    AND METADATA$ACTION='INSERT'
    AND METADATA$ISUPDATE=FALSE
THEN INSERT (EMPID,EMPNAME,SALARY,AGE,DEPT,LOCATION, INSERT_DATE,LAST_UPDATE_DATE) 
     VALUES (S.EMPID,S.EMPNAME,S.SALARY,S.AGE,S.DEPT,S.LOCATION,CURRENT_DATE,NULL);

 Alter task MY_DB.SCHEMA3.Stream_TASK Resume;
  Alter task MY_DB.SCHEMA3.Stream_TASK SUSPEND;
 
 show Tasks in schema schema3;
 Select * from table (Information_schema.TASK_HISTORY());
 
Select * from MY_DB.SCHEMA3.STG_EMPL;

INSERT INTO MY_DB.SCHEMA3.STG_EMPL
VALUES
(9, 'LATA',47000,35,'HR','Chennai');

DELETE FROM MY_DB.SCHEMA3.STG_EMPL WHERE EMPID in (5);

UPDATE MY_DB.SCHEMA3.STG_EMPL SET SALARY = 67000 where EMPID = 7; 
     

Select * from MY_DB.SCHEMA3.STREAM_EMPL1;

Select * from MY_DB.SCHEMA3.TARGET_EMPL;

select to_timestamp_ltz(CUrrent_timestamp)